// Mock data for the enhanced simulation

import { Station, Driver, KPIMetrics, DemandConfig, PricingConfig, InventoryConfig } from './types';

// IEX Day-Ahead Market wholesale price curve (Rs/kWh) — 24 hourly values based on published IEX DAM patterns
export const IEX_WHOLESALE_PRICE_CURVE: number[] = [
    3.2, 2.8, 2.5, 2.3, 2.4, 3.0, 4.5, 6.0, 7.2, 6.8,
    6.2, 5.8, 5.5, 5.2, 5.0, 5.3, 6.0, 7.5, 8.5, 8.0,
    7.0, 5.5, 4.2, 3.5,
];

// Delhi Time-of-Day tariff multipliers — 24 hourly values
export const DELHI_TOD_MULTIPLIERS: number[] = [
    0.75, 0.75, 0.75, 0.75, 0.75, 0.85, 1.0, 1.2, 1.3, 1.2,
    1.1, 1.0, 1.0, 1.0, 1.0, 1.1, 1.2, 1.4, 1.5, 1.4,
    1.2, 1.0, 0.85, 0.75,
];

// Charger power in kW (DC fast charger)
export const CHARGER_POWER_KW = 50;

// Pool of Indian driver names
export const DRIVER_NAMES: string[] = [
    'Rajesh Kumar', 'Amit Sharma', 'Priya Singh', 'Vikram Patel', 'Sunita Verma',
    'Deepak Gupta', 'Neha Agarwal', 'Suresh Yadav', 'Kavita Joshi', 'Manoj Tiwari',
    'Anita Reddy', 'Rahul Mishra', 'Pooja Chauhan', 'Sanjay Dubey', 'Meena Pandey',
    'Arun Saxena', 'Rekha Bhat', 'Vijay Nair', 'Ritu Kapoor', 'Ashok Malhotra',
    'Geeta Iyer', 'Ravi Menon', 'Seema Pillai', 'Kiran Deshmukh', 'Ajay Thakur',
    'Lata Kulkarni', 'Mohan Das', 'Nisha Choudhary', 'Pankaj Srivastava', 'Uma Mehta',
    'Harish Bansal', 'Divya Rastogi', 'Nitin Bhargava', 'Sarita Devi', 'Ramesh Awasthi',
];

export function generateVehicleId(): string {
    const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const stateCode = 'DL';
    const series = Math.floor(Math.random() * 14) + 1;
    const l1 = letters[Math.floor(Math.random() * 26)];
    const l2 = letters[Math.floor(Math.random() * 26)];
    const num = Math.floor(Math.random() * 9000) + 1000;
    return `${stateCode}${series.toString().padStart(2, '0')}${l1}${l2}${num}`;
}

export const initialStations: Station[] = [
    {
        id: 'station-1',
        name: 'Central Hub',
        location: 'Connaught Place',
        position: { x: 50, y: 45 },
        geoPosition: { lat: 28.6315, lng: 77.2167 },
        chargers: 12,
        activeChargers: 12,
        chargerType: 'mixed',
        bays: 60,
        inventoryCap: 50,
        currentInventory: 42,
        chargingBatteries: 8,
        queueLength: 3,
        status: 'operational',
        utilizationRate: 0.85,
        avgWaitTime: 4.2,
        totalSwaps: 156,
        lostSwaps: 4,
        peakQueueLength: 8,
        operatingHours: { start: 0, end: 24 },
        coverageRadius: 3,
    },
    {
        id: 'station-2',
        name: 'North Terminal',
        location: 'Civil Lines',
        position: { x: 45, y: 20 },
        geoPosition: { lat: 28.6814, lng: 77.2226 },
        chargers: 8,
        activeChargers: 8,
        chargerType: 'standard',
        bays: 40,
        inventoryCap: 35,
        currentInventory: 28,
        chargingBatteries: 5,
        queueLength: 1,
        status: 'operational',
        utilizationRate: 0.72,
        avgWaitTime: 2.8,
        totalSwaps: 98,
        lostSwaps: 1,
        peakQueueLength: 5,
        operatingHours: { start: 6, end: 23 },
        coverageRadius: 2.5,
    },
    {
        id: 'station-3',
        name: 'East Gateway',
        location: 'Laxmi Nagar',
        position: { x: 78, y: 35 },
        geoPosition: { lat: 28.6304, lng: 77.2772 },
        chargers: 10,
        activeChargers: 10,
        chargerType: 'fast',
        bays: 50,
        inventoryCap: 40,
        currentInventory: 15,
        chargingBatteries: 10,
        queueLength: 5,
        status: 'low_inventory',
        utilizationRate: 0.95,
        avgWaitTime: 6.5,
        totalSwaps: 145,
        lostSwaps: 12,
        peakQueueLength: 12,
        operatingHours: { start: 0, end: 24 },
        coverageRadius: 3,
    },
    {
        id: 'station-4',
        name: 'South Plaza',
        location: 'Saket',
        position: { x: 40, y: 75 },
        geoPosition: { lat: 28.5244, lng: 77.2066 },
        chargers: 6,
        activeChargers: 6,
        chargerType: 'standard',
        bays: 30,
        inventoryCap: 25,
        currentInventory: 22,
        chargingBatteries: 3,
        queueLength: 0,
        status: 'operational',
        utilizationRate: 0.45,
        avgWaitTime: 1.2,
        totalSwaps: 67,
        lostSwaps: 0,
        peakQueueLength: 3,
        operatingHours: { start: 6, end: 22 },
        coverageRadius: 2,
    },
    {
        id: 'station-5',
        name: 'West Junction',
        location: 'Janakpuri',
        position: { x: 18, y: 50 },
        geoPosition: { lat: 28.6219, lng: 77.0878 },
        chargers: 8,
        activeChargers: 8,
        chargerType: 'mixed',
        bays: 40,
        inventoryCap: 30,
        currentInventory: 26,
        chargingBatteries: 4,
        queueLength: 2,
        status: 'operational',
        utilizationRate: 0.68,
        avgWaitTime: 3.1,
        totalSwaps: 112,
        lostSwaps: 2,
        peakQueueLength: 6,
        operatingHours: { start: 5, end: 24 },
        coverageRadius: 3,
    },
    {
        id: 'station-6',
        name: 'Airport Express',
        location: 'IGI Airport',
        position: { x: 85, y: 65 },
        geoPosition: { lat: 28.5562, lng: 77.1000 },
        chargers: 15,
        activeChargers: 15,
        chargerType: 'fast',
        bays: 80,
        inventoryCap: 60,
        currentInventory: 48,
        chargingBatteries: 12,
        queueLength: 4,
        status: 'operational',
        utilizationRate: 0.82,
        avgWaitTime: 3.8,
        totalSwaps: 234,
        lostSwaps: 6,
        peakQueueLength: 10,
        operatingHours: { start: 0, end: 24 },
        coverageRadius: 4,
    },
    {
        id: 'station-7',
        name: 'Tech Park',
        location: 'Noida Sector 62',
        position: { x: 65, y: 55 },
        geoPosition: { lat: 28.6270, lng: 77.3653 },
        chargers: 10,
        activeChargers: 7,
        chargerType: 'fast',
        bays: 50,
        inventoryCap: 35,
        currentInventory: 30,
        chargingBatteries: 5,
        queueLength: 6,
        status: 'overloaded',
        utilizationRate: 0.98,
        avgWaitTime: 8.2,
        totalSwaps: 178,
        lostSwaps: 15,
        peakQueueLength: 15,
        operatingHours: { start: 7, end: 22 },
        coverageRadius: 2.5,
    },
    {
        id: 'station-8',
        name: 'University District',
        location: 'North Campus',
        position: { x: 30, y: 30 },
        geoPosition: { lat: 28.6862, lng: 77.2095 },
        chargers: 6,
        activeChargers: 6,
        chargerType: 'standard',
        bays: 30,
        inventoryCap: 20,
        currentInventory: 18,
        chargingBatteries: 2,
        queueLength: 1,
        status: 'operational',
        utilizationRate: 0.55,
        avgWaitTime: 2.0,
        totalSwaps: 89,
        lostSwaps: 1,
        peakQueueLength: 4,
        operatingHours: { start: 6, end: 23 },
        coverageRadius: 2,
    },
    // 12 new stations across Delhi NCR
    {
        id: 'station-9',
        name: 'Dwarka Central',
        location: 'Dwarka Sector 21',
        position: { x: 10, y: 65 },
        geoPosition: { lat: 28.5523, lng: 77.0586 },
        chargers: 10,
        activeChargers: 10,
        chargerType: 'mixed',
        bays: 50,
        inventoryCap: 40,
        currentInventory: 34,
        chargingBatteries: 6,
        queueLength: 2,
        status: 'operational',
        utilizationRate: 0.70,
        avgWaitTime: 3.0,
        totalSwaps: 120,
        lostSwaps: 3,
        peakQueueLength: 7,
        operatingHours: { start: 5, end: 24 },
        coverageRadius: 3,
    },
    {
        id: 'station-10',
        name: 'Gurgaon Hub',
        location: 'Cyber City',
        position: { x: 25, y: 85 },
        geoPosition: { lat: 28.4940, lng: 77.0888 },
        chargers: 14,
        activeChargers: 14,
        chargerType: 'fast',
        bays: 70,
        inventoryCap: 55,
        currentInventory: 45,
        chargingBatteries: 10,
        queueLength: 3,
        status: 'operational',
        utilizationRate: 0.78,
        avgWaitTime: 3.5,
        totalSwaps: 210,
        lostSwaps: 5,
        peakQueueLength: 9,
        operatingHours: { start: 0, end: 24 },
        coverageRadius: 4,
    },
    {
        id: 'station-11',
        name: 'Faridabad Point',
        location: 'Sector 15',
        position: { x: 65, y: 90 },
        geoPosition: { lat: 28.4089, lng: 77.3178 },
        chargers: 8,
        activeChargers: 8,
        chargerType: 'standard',
        bays: 40,
        inventoryCap: 30,
        currentInventory: 25,
        chargingBatteries: 4,
        queueLength: 1,
        status: 'operational',
        utilizationRate: 0.60,
        avgWaitTime: 2.5,
        totalSwaps: 85,
        lostSwaps: 2,
        peakQueueLength: 5,
        operatingHours: { start: 6, end: 23 },
        coverageRadius: 2.5,
    },
    {
        id: 'station-12',
        name: 'Greater Noida',
        location: 'Pari Chowk',
        position: { x: 90, y: 70 },
        geoPosition: { lat: 28.4744, lng: 77.5040 },
        chargers: 12,
        activeChargers: 12,
        chargerType: 'fast',
        bays: 60,
        inventoryCap: 45,
        currentInventory: 38,
        chargingBatteries: 7,
        queueLength: 2,
        status: 'operational',
        utilizationRate: 0.65,
        avgWaitTime: 2.8,
        totalSwaps: 130,
        lostSwaps: 3,
        peakQueueLength: 6,
        operatingHours: { start: 0, end: 24 },
        coverageRadius: 3.5,
    },
    {
        id: 'station-13',
        name: 'Rohini Plaza',
        location: 'Sector 7',
        position: { x: 32, y: 15 },
        geoPosition: { lat: 28.7157, lng: 77.1150 },
        chargers: 10,
        activeChargers: 10,
        chargerType: 'mixed',
        bays: 50,
        inventoryCap: 35,
        currentInventory: 30,
        chargingBatteries: 5,
        queueLength: 2,
        status: 'operational',
        utilizationRate: 0.62,
        avgWaitTime: 2.6,
        totalSwaps: 105,
        lostSwaps: 2,
        peakQueueLength: 6,
        operatingHours: { start: 6, end: 23 },
        coverageRadius: 2.5,
    },
    {
        id: 'station-14',
        name: 'Pitampura Station',
        location: 'Netaji Subhash Place',
        position: { x: 38, y: 10 },
        geoPosition: { lat: 28.6970, lng: 77.1587 },
        chargers: 8,
        activeChargers: 8,
        chargerType: 'standard',
        bays: 40,
        inventoryCap: 30,
        currentInventory: 26,
        chargingBatteries: 4,
        queueLength: 1,
        status: 'operational',
        utilizationRate: 0.58,
        avgWaitTime: 2.2,
        totalSwaps: 92,
        lostSwaps: 1,
        peakQueueLength: 4,
        operatingHours: { start: 6, end: 22 },
        coverageRadius: 2,
    },
    {
        id: 'station-15',
        name: 'Nehru Place',
        location: 'Nehru Place',
        position: { x: 55, y: 68 },
        geoPosition: { lat: 28.5491, lng: 77.2533 },
        chargers: 10,
        activeChargers: 10,
        chargerType: 'fast',
        bays: 50,
        inventoryCap: 40,
        currentInventory: 32,
        chargingBatteries: 8,
        queueLength: 3,
        status: 'operational',
        utilizationRate: 0.75,
        avgWaitTime: 3.4,
        totalSwaps: 140,
        lostSwaps: 4,
        peakQueueLength: 8,
        operatingHours: { start: 7, end: 23 },
        coverageRadius: 2.5,
    },
    {
        id: 'station-16',
        name: 'Karol Bagh',
        location: 'Karol Bagh',
        position: { x: 40, y: 38 },
        geoPosition: { lat: 28.6514, lng: 77.1907 },
        chargers: 8,
        activeChargers: 8,
        chargerType: 'mixed',
        bays: 40,
        inventoryCap: 30,
        currentInventory: 24,
        chargingBatteries: 5,
        queueLength: 2,
        status: 'operational',
        utilizationRate: 0.72,
        avgWaitTime: 3.0,
        totalSwaps: 108,
        lostSwaps: 2,
        peakQueueLength: 6,
        operatingHours: { start: 6, end: 23 },
        coverageRadius: 2,
    },
    {
        id: 'station-17',
        name: 'Rajouri Garden',
        location: 'Rajouri Garden',
        position: { x: 25, y: 42 },
        geoPosition: { lat: 28.6492, lng: 77.1230 },
        chargers: 8,
        activeChargers: 8,
        chargerType: 'standard',
        bays: 40,
        inventoryCap: 30,
        currentInventory: 27,
        chargingBatteries: 3,
        queueLength: 1,
        status: 'operational',
        utilizationRate: 0.52,
        avgWaitTime: 2.0,
        totalSwaps: 78,
        lostSwaps: 1,
        peakQueueLength: 4,
        operatingHours: { start: 6, end: 22 },
        coverageRadius: 2,
    },
    {
        id: 'station-18',
        name: 'Vasant Kunj',
        location: 'Vasant Kunj',
        position: { x: 30, y: 78 },
        geoPosition: { lat: 28.5195, lng: 77.1587 },
        chargers: 10,
        activeChargers: 10,
        chargerType: 'mixed',
        bays: 50,
        inventoryCap: 35,
        currentInventory: 30,
        chargingBatteries: 5,
        queueLength: 2,
        status: 'operational',
        utilizationRate: 0.62,
        avgWaitTime: 2.5,
        totalSwaps: 95,
        lostSwaps: 2,
        peakQueueLength: 5,
        operatingHours: { start: 5, end: 24 },
        coverageRadius: 3,
    },
    {
        id: 'station-19',
        name: 'Mayur Vihar',
        location: 'Mayur Vihar Phase 1',
        position: { x: 72, y: 48 },
        geoPosition: { lat: 28.5935, lng: 77.2980 },
        chargers: 10,
        activeChargers: 10,
        chargerType: 'fast',
        bays: 50,
        inventoryCap: 35,
        currentInventory: 28,
        chargingBatteries: 6,
        queueLength: 3,
        status: 'operational',
        utilizationRate: 0.74,
        avgWaitTime: 3.2,
        totalSwaps: 125,
        lostSwaps: 3,
        peakQueueLength: 7,
        operatingHours: { start: 6, end: 23 },
        coverageRadius: 2.5,
    },
    {
        id: 'station-20',
        name: 'Chandni Chowk',
        location: 'Chandni Chowk',
        position: { x: 52, y: 30 },
        geoPosition: { lat: 28.6506, lng: 77.2302 },
        chargers: 8,
        activeChargers: 8,
        chargerType: 'standard',
        bays: 40,
        inventoryCap: 30,
        currentInventory: 25,
        chargingBatteries: 4,
        queueLength: 2,
        status: 'operational',
        utilizationRate: 0.68,
        avgWaitTime: 2.8,
        totalSwaps: 102,
        lostSwaps: 2,
        peakQueueLength: 6,
        operatingHours: { start: 7, end: 22 },
        coverageRadius: 2,
    },
];

export const initialDrivers: Driver[] = [
    { id: 'driver-1', name: 'Rajesh Kumar', vehicleId: 'DL01AB1234', position: { x: 55, y: 40 }, targetStationId: 'station-1', status: 'en_route', eta: 2, batteryLevel: 'normal', batteryPercent: 62, swapsToday: 2, amountOwed: 198 },
    { id: 'driver-2', name: 'Amit Sharma', vehicleId: 'DL05CD5678', position: { x: 70, y: 30 }, targetStationId: 'station-3', status: 'en_route', eta: 3, batteryLevel: 'low', batteryPercent: 35, swapsToday: 3, amountOwed: 296 },
    { id: 'driver-3', name: 'Priya Singh', vehicleId: 'DL12EF9012', position: { x: 35, y: 70 }, targetStationId: 'station-4', status: 'swapping', eta: 0, batteryLevel: 'critical', batteryPercent: 8, swapsToday: 1, amountOwed: 99 },
    { id: 'driver-4', name: 'Vikram Patel', vehicleId: 'DL08GH3456', position: { x: 80, y: 60 }, targetStationId: 'station-6', status: 'seeking', eta: 5, batteryLevel: 'normal', batteryPercent: 71, swapsToday: 0, amountOwed: 0 },
    { id: 'driver-5', name: 'Sunita Verma', vehicleId: 'DL03IJ7890', position: { x: 25, y: 45 }, targetStationId: 'station-5', status: 'en_route', eta: 1, batteryLevel: 'low', batteryPercent: 28, swapsToday: 4, amountOwed: 392 },
    { id: 'driver-6', name: 'Deepak Gupta', vehicleId: 'DL10KL2345', position: { x: 60, y: 50 }, targetStationId: 'station-7', status: 'en_route', eta: 2, batteryLevel: 'normal', batteryPercent: 55, swapsToday: 1, amountOwed: 99 },
    { id: 'driver-7', name: 'Neha Agarwal', vehicleId: 'DL07MN6789', position: { x: 45, y: 25 }, targetStationId: 'station-2', status: 'en_route', eta: 1, batteryLevel: 'critical', batteryPercent: 12, swapsToday: 5, amountOwed: 490 },
    { id: 'driver-8', name: 'Suresh Yadav', vehicleId: 'DL14OP0123', position: { x: 52, y: 48 }, targetStationId: 'station-1', status: 'swapping', eta: 0, batteryLevel: 'normal', batteryPercent: 48, swapsToday: 2, amountOwed: 198 },
];

export const demandCurves: number[] = [
    0.2, 0.15, 0.1, 0.1, 0.15, 0.3, 0.5, 0.8, 1.0, 0.9,
    0.75, 0.7, 0.85, 0.8, 0.75, 0.7, 0.8, 0.95, 1.0, 0.85,
    0.65, 0.5, 0.35, 0.25,
];

export const baselineKPIs: KPIMetrics = {
    avgWaitTime: 3.8,
    lostSwaps: 24,
    idleInventory: 45,
    chargerUtilization: 0.72,
    operationalCost: 125000,
    cityThroughput: 842,
    reroutedDrivers: 0,
    emergencyEvents: 0,
    revenue: 450000,
    peakWaitTime: 8.2,
    averageQueueLength: 2.8,
};

export const defaultDemandConfig: DemandConfig = {
    weatherMultiplier: 1.0,
    timeOfDayModifiers: demandCurves,
};

export const defaultPricingConfig: PricingConfig = {
    strategy: 'flat',
    peakMultiplier: 1.0,
    offPeakDiscount: 0,
    peakHours: { start: 8, end: 20 },
};

export const defaultInventoryConfig: InventoryConfig = {
    safetyStock: 10,
    rebalanceThreshold: 30,
    rebalanceFrequency: 4,
};
