// Mock data for the enhanced simulation

import { Station, Driver, KPIMetrics, DemandConfig, PricingConfig, InventoryConfig } from './types';

export const initialStations: Station[] = [
    {
        id: 'station-1',
        name: 'Central Hub',
        location: 'Connaught Place',
        position: { x: 50, y: 45 },
        chargers: 12,
        activeChargers: 12,
        chargerType: 'mixed',
        bays: 60,
        inventoryCap: 50,
        currentInventory: 42,
        chargingBatteries: 8,
        queueLength: 3,
        status: 'operational',
        utilizationRate: 0.85,
        avgWaitTime: 4.2,
        totalSwaps: 156,
        lostSwaps: 4,
        peakQueueLength: 8,
        operatingHours: { start: 0, end: 24 },
        coverageRadius: 3,
    },
    {
        id: 'station-2',
        name: 'North Terminal',
        location: 'Civil Lines',
        position: { x: 45, y: 20 },
        chargers: 8,
        activeChargers: 8,
        chargerType: 'standard',
        bays: 40,
        inventoryCap: 35,
        currentInventory: 28,
        chargingBatteries: 5,
        queueLength: 1,
        status: 'operational',
        utilizationRate: 0.72,
        avgWaitTime: 2.8,
        totalSwaps: 98,
        lostSwaps: 1,
        peakQueueLength: 5,
        operatingHours: { start: 6, end: 23 },
        coverageRadius: 2.5,
    },
    {
        id: 'station-3',
        name: 'East Gateway',
        location: 'Laxmi Nagar',
        position: { x: 78, y: 35 },
        chargers: 10,
        activeChargers: 10,
        chargerType: 'fast',
        bays: 50,
        inventoryCap: 40,
        currentInventory: 15,
        chargingBatteries: 10,
        queueLength: 5,
        status: 'low_inventory',
        utilizationRate: 0.95,
        avgWaitTime: 6.5,
        totalSwaps: 145,
        lostSwaps: 12,
        peakQueueLength: 12,
        operatingHours: { start: 0, end: 24 },
        coverageRadius: 3,
    },
    {
        id: 'station-4',
        name: 'South Plaza',
        location: 'Saket',
        position: { x: 40, y: 75 },
        chargers: 6,
        activeChargers: 6,
        chargerType: 'standard',
        bays: 30,
        inventoryCap: 25,
        currentInventory: 22,
        chargingBatteries: 3,
        queueLength: 0,
        status: 'operational',
        utilizationRate: 0.45,
        avgWaitTime: 1.2,
        totalSwaps: 67,
        lostSwaps: 0,
        peakQueueLength: 3,
        operatingHours: { start: 6, end: 22 },
        coverageRadius: 2,
    },
    {
        id: 'station-5',
        name: 'West Junction',
        location: 'Janakpuri',
        position: { x: 18, y: 50 },
        chargers: 8,
        activeChargers: 8,
        chargerType: 'mixed',
        bays: 40,
        inventoryCap: 30,
        currentInventory: 26,
        chargingBatteries: 4,
        queueLength: 2,
        status: 'operational',
        utilizationRate: 0.68,
        avgWaitTime: 3.1,
        totalSwaps: 112,
        lostSwaps: 2,
        peakQueueLength: 6,
        operatingHours: { start: 5, end: 24 },
        coverageRadius: 3,
    },
    {
        id: 'station-6',
        name: 'Airport Express',
        location: 'IGI Airport',
        position: { x: 85, y: 65 },
        chargers: 15,
        activeChargers: 15,
        chargerType: 'fast',
        bays: 80,
        inventoryCap: 60,
        currentInventory: 48,
        chargingBatteries: 12,
        queueLength: 4,
        status: 'operational',
        utilizationRate: 0.82,
        avgWaitTime: 3.8,
        totalSwaps: 234,
        lostSwaps: 6,
        peakQueueLength: 10,
        operatingHours: { start: 0, end: 24 },
        coverageRadius: 4,
    },
    {
        id: 'station-7',
        name: 'Tech Park',
        location: 'Noida Sector 62',
        position: { x: 65, y: 55 },
        chargers: 10,
        activeChargers: 7,
        chargerType: 'fast',
        bays: 50,
        inventoryCap: 35,
        currentInventory: 30,
        chargingBatteries: 5,
        queueLength: 6,
        status: 'overloaded',
        utilizationRate: 0.98,
        avgWaitTime: 8.2,
        totalSwaps: 178,
        lostSwaps: 15,
        peakQueueLength: 15,
        operatingHours: { start: 7, end: 22 },
        coverageRadius: 2.5,
    },
    {
        id: 'station-8',
        name: 'University District',
        location: 'North Campus',
        position: { x: 30, y: 30 },
        chargers: 6,
        activeChargers: 6,
        chargerType: 'standard',
        bays: 30,
        inventoryCap: 20,
        currentInventory: 18,
        chargingBatteries: 2,
        queueLength: 1,
        status: 'operational',
        utilizationRate: 0.55,
        avgWaitTime: 2.0,
        totalSwaps: 89,
        lostSwaps: 1,
        peakQueueLength: 4,
        operatingHours: { start: 6, end: 23 },
        coverageRadius: 2,
    },
];

export const initialDrivers: Driver[] = [
    { id: 'driver-1', position: { x: 55, y: 40 }, targetStationId: 'station-1', status: 'en_route', eta: 2, batteryLevel: 'normal' },
    { id: 'driver-2', position: { x: 70, y: 30 }, targetStationId: 'station-3', status: 'en_route', eta: 3, batteryLevel: 'low' },
    { id: 'driver-3', position: { x: 35, y: 70 }, targetStationId: 'station-4', status: 'swapping', eta: 0, batteryLevel: 'critical' },
    { id: 'driver-4', position: { x: 80, y: 60 }, targetStationId: 'station-6', status: 'seeking', eta: 5, batteryLevel: 'normal' },
    { id: 'driver-5', position: { x: 25, y: 45 }, targetStationId: 'station-5', status: 'en_route', eta: 1, batteryLevel: 'low' },
    { id: 'driver-6', position: { x: 60, y: 50 }, targetStationId: 'station-7', status: 'en_route', eta: 2, batteryLevel: 'normal' },
    { id: 'driver-7', position: { x: 45, y: 25 }, targetStationId: 'station-2', status: 'en_route', eta: 1, batteryLevel: 'critical' },
    { id: 'driver-8', position: { x: 52, y: 48 }, targetStationId: 'station-1', status: 'swapping', eta: 0, batteryLevel: 'normal' },
];

export const demandCurves: number[] = [
    0.2, 0.15, 0.1, 0.1, 0.15, 0.3, 0.5, 0.8, 1.0, 0.9,
    0.75, 0.7, 0.85, 0.8, 0.75, 0.7, 0.8, 0.95, 1.0, 0.85,
    0.65, 0.5, 0.35, 0.25,
];

export const baselineKPIs: KPIMetrics = {
    avgWaitTime: 3.8,
    lostSwaps: 24,
    idleInventory: 45,
    chargerUtilization: 0.72,
    operationalCost: 125000,
    cityThroughput: 842,
    reroutedDrivers: 0,
    emergencyEvents: 0,
    revenue: 450000,
    peakWaitTime: 8.2,
    averageQueueLength: 2.8,
};

export const defaultDemandConfig: DemandConfig = {
    weatherMultiplier: 1.0,
    timeOfDayModifiers: demandCurves,
};

export const defaultPricingConfig: PricingConfig = {
    strategy: 'flat',
    peakMultiplier: 1.0,
    offPeakDiscount: 0,
    peakHours: { start: 8, end: 20 },
};

export const defaultInventoryConfig: InventoryConfig = {
    safetyStock: 10,
    rebalanceThreshold: 30,
    rebalanceFrequency: 4,
};
